# Use postgres/example user/password credentials
version: '3.9'

services:

  # Postgres database
  db:
    build: ./image/postgres/
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    ports:
      - "5432:5432" # 左側がホストのポート、右側がコンテナのポート
    container_name: postgres-db

    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - ./postgres/data:/var/lib/postgresql/data # 左側がホストのディレクトリ、右側がコンテナのディレクトリ
      - ./postgres/initdb:/docker-entrypoint-initdb.d # 初期化SQLなど

    
